# Code to calculate distance from one country (its capital) to another

In [ ]:
#!pip install pandas geopy

In [2]:
import csv
from geopy.distance import great_circle
import pandas as pd

In [7]:
capitals = pd.read_csv("country_to_continent.csv")

def calculate_distances():
    distance_data = []

    for index_from, capital_from in capitals.iterrows():
        from_coords = (capital_from["Latitude"], capital_from["Longitude"])

        for index_to, capital_to in capitals.iterrows():
            if capital_from["Capital"] != capital_to["Capital"]:
                to_coords = (capital_to["Latitude"], capital_to["Longitude"])
                distance = great_circle(from_coords, to_coords).kilometers
                distance_data.append({
                    "country_from": capital_from["Country"],
                    "capital_from": capital_from["Capital"],
                    "country_to": capital_to["Country"],
                    "capital_to": capital_to["Capital"],
                    "distance_in_km": distance
                })

    return pd.DataFrame(distance_data)

In [12]:
# Generate the dataframe with all combinations of distances
distance_df = calculate_distances()

# Save the dataframe to a new CSV file if needed
distance_df.to_csv('country_distances.csv', index=False)

In [11]:
distance_df[distance_df['country_from'] == "Argentina"]

      country_from  capital_from    country_to      capital_to  distance_in_km
39548    Argentina  Buenos Aires       Algeria         Algiers    10167.356400
39549    Argentina  Buenos Aires        Angola          Luanda     7780.055521
39550    Argentina  Buenos Aires         Benin      Porto-Novo     7854.168596
39551    Argentina  Buenos Aires      Botswana        Gaborone     7996.190918
39552    Argentina  Buenos Aires  Burkina Faso     Ouagadougou     7949.361258
...            ...           ...           ...             ...             ...
39749    Argentina  Buenos Aires       Uruguay      Montevideo      208.300837
39750    Argentina  Buenos Aires     Venezuela         Caracas     5093.271019
39751    Argentina  Buenos Aires     Palestine  East Jerusalem    12240.574336
39752    Argentina  Buenos Aires        Taiwan          Taipei    18949.998301
39753    Argentina  Buenos Aires        Kosovo        Pristina    11785.785581

[206 rows x 5 columns]