# Determine if a country is an island or not

To use it to consider ways of trading

In [1]:
import pandas as pd
import numpy as np

In [2]:
distance_df = pd.read_csv(r"..\data\FAOSTAT\clean_data\food_trading\country_distances_matrix.csv")

In [3]:
distance_df.head()

,country_from,continent_from,country_to,Continent_to,distance_in_km,same_continent,share_border
0,Afghanistan,Asia,Afghanistan,Asia,0.000000,1,1.0
1,Afghanistan,Asia,Albania,Europe,4335.926901,0,0.0
2,Afghanistan,Asia,Algeria,Africa,5855.362822,0,0.0
3,Afghanistan,Asia,Andorra,Europe,5796.993207,0,NaN
4,Afghanistan,Asia,Angola,Africa,7596.963990,0,0.0

In [4]:
border_nr_df = distance_df.groupby('country_from')['share_border'].sum().to_frame() #number of border countries (including itself)

In [5]:
border_nr_df.sort_values(by='share_border', ascending=True)

                 share_border
country_from
Faroe Islands             1.0
Madagascar                1.0
Nauru                     1.0
Réunion                   1.0
Maldives                  1.0
...                       ...
Zambia                   10.0
Brazil                   11.0
Russia                   15.0
China                    15.0
Dem. Rep. Congo          20.0

[224 rows x 1 columns]

If only shares border with itself = Island or missing info

In [12]:
border_nr_df[border_nr_df['share_border'] == 1]

                                              share_border
country_from
Andorra                                                1.0
Antigua and Barbuda                                    1.0
Australia                                              1.0
Bahamas                                                1.0
Bahrain                                                1.0
Barbados                                               1.0
Bouvet Island                                          1.0
Cabo Verde                                             1.0
Canton and Enderbury Islands                           1.0
Cape Verde                                             1.0
Comoros                                                1.0
Cook Islands                                           1.0
Cuba                                                   1.0
Cyprus                                                 1.0
Czechoslovakia                                         1.0
Dominica                                               1.0
Faroe Islands                                          1.0
Fiji                                                   1.0
French Polynesia                                       1.0
Grenada                                                1.0
Guadeloupe                                             1.0
Heard and McDonald Islands                             1.0
Iceland                                                1.0
Jamaica                                                1.0
Japan                                                  1.0
Johnston Atoll                                         1.0
Kiribati                                               1.0
Liechtenstein                                          1.0
Madagascar                                             1.0
Maldives                                               1.0
Malta                                                  1.0
Marshall Islands                                       1.0
Martinique                                             1.0
Mauritius                                              1.0
Micronesia (federated states of)                       1.0
Midway Atoll                                           1.0
Monaco                                                 1.0
Nauru                                                  1.0
New Caledonia                                          1.0
New Zealand                                            1.0
Niue                                                   1.0
Palau                                                  1.0
Philippines                                            1.0
Puerto Rico                                            1.0
Réunion                                                1.0
Saint Barthélemy                                       1.0
Saint Kitts and Nevis                                  1.0
Saint Lucia                                            1.0
Saint Martin                                           1.0
Saint Vincent and the Grenadines                       1.0
Samoa                                                  1.0
San Marino                                             1.0
Sao Tome and Principe                                  1.0
Serbia and Montenegro                                  1.0
Seychelles                                             1.0
Singapore                                              1.0
Sint Eustatius                                         1.0
Sint Maarten                                           1.0
Solomon Is.                                            1.0
South Georgia and the South Sandwich Islands           1.0
Sri Lanka                                              1.0
Svalbard and Jan Mayen                                 1.0
Taiwan                                                 1.0
Tokelau                                                1.0
Tonga                                                  1.0
Trinidad and Tobago                                    1.0
Tuvalu                                                 1.0
USSR                                                   1.0
Vanuatu                                                1.0
Vatican City                                           1.0
Wake Island                                            1.0
Western Sahara                                         1.0
Yugoslavia                                             1.0

In [19]:
no_border_countries = border_nr_df[border_nr_df['share_border'] == 1].index.to_list()

island_countries_chatGPT = [ #country islands from chatGPT
    "Antigua and Barbuda",
    "Bahamas",
    "Bahrain",
    "Barbados",
    "Cape Verde (Cabo Verde)",
    "Comoros",
    "Cuba",
    "Cyprus",
    "Dominica",
    "Dominican Republic",
    "East Timor (Timor-Leste)",
    "Fiji",
    "Grenada",
    "Iceland",
    "Indonesia",
    "Ireland",
    "Jamaica",
    "Japan",
    "Kiribati",
    "Madagascar",
    "Maldives",
    "Malta",
    "Marshall Islands",
    "Mauritius",
    "Micronesia (Federated States of Micronesia)",
    "Nauru",
    "New Zealand",
    "Palau",
    "Papua New Guinea",
    "Philippines",
    "Samoa",
    "São Tomé and Príncipe",
    "Seychelles",
    "Singapore",
    "Solomon Islands",
    "Sri Lanka",
    "St. Kitts and Nevis",
    "St. Lucia",
    "St. Vincent and the Grenadines",
    "Tonga",
    "Trinidad and Tobago",
    "Tuvalu",
    "United Kingdom",
    "Vanuatu"
]

In [20]:
island_countries_chatGPT.extend(no_border_countries)
all_islands_ormissing_list = [item.lower() for item in island_countries_chatGPT]

In [26]:
distance_df['any_island_or_missing'] = np.where(distance_df['country_from'].isin(set(all_islands_ormissing_list)) | distance_df['country_to'].isin(set(all_islands_ormissing_list)), 1, 0)

In [27]:
distance_df.to_csv(r"..\data\FAOSTAT\clean_data\food_trading\country_distances_matrix_border_island.csv", index=False)